name: ai_assistant
description: AI Assistant app powered by Gemini API with Material Design 3
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.0
  flutter_markdown: ^0.6.18
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
