#!/bin/bash

echo "=================================="
echo "AI Assistant - Flutter Project"
echo "=================================="
echo ""
echo "Thông tin dự án:"
echo "- Ngôn ngữ: Flutter (Dart)"
echo "- Platform: Android"
echo "- Material Design: 3"
echo "- AI Engine: Gemini API"
echo ""
echo "Tính năng:"
echo "✓ Chat interface với Material Design 3"
echo "✓ Tích hợp Gemini API"
echo "✓ Voice input (speech-to-text)"
echo "✓ Quick Settings Tile"
echo "✓ App Shortcuts"
echo "✓ Chat history với local storage"
echo "✓ GitHub Actions auto-build APK"
echo ""
echo "Cấu trúc dự án:"
echo "✓ pubspec.yaml - Flutter dependencies"
echo "✓ lib/ - Flutter source code"
echo "✓ android/ - Android native code"
echo "✓ .github/workflows/ - CI/CD configuration"
echo ""
echo "=================================="
echo "Hướng dẫn build APK:"
echo "=================================="
echo ""
echo "CÁCH 1: Build tự động với GitHub Actions"
echo "  1. Push code lên GitHub repository"
echo "  2. GitHub Actions sẽ tự động build APK"
echo "  3. Tải APK từ Actions > Artifacts"
echo ""
echo "CÁCH 2: Build thủ công (yêu cầu Flutter SDK)"
echo "  1. Cài đặt Flutter SDK: https://flutter.dev/docs/get-started/install"
echo "  2. Chạy: flutter pub get"
echo "  3. Chạy: flutter build apk --release"
echo "  4. APK tại: build/app/outputs/flutter-apk/"
echo ""
echo "=================================="
echo "Lưu ý quan trọng:"
echo "=================================="
echo ""
echo "⚠ Dự án này là Flutter Android app và không thể chạy trực tiếp trên Replit"
echo "⚠ Cần Flutter SDK và Android SDK để build và test"
echo "⚠ Sử dụng GitHub Actions để build APK tự động"
echo "⚠ Cần Gemini API Key để sử dụng chức năng AI"
echo ""
echo "📱 Lấy Gemini API Key tại: https://makersuite.google.com/app/apikey"
echo ""
echo "Dự án đã sẵn sàng để push lên GitHub!"
echo ""
